# Generated by Django 4.0.1 on 2022-01-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a province name', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the route name', max_length=100)),
                ('length', models.IntegerField(help_text='Enter the length of the route', max_length=3)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='route.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
