# Generated by Django 4.0.1 on 2022-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.IntegerField(help_text='Enter the length of the route'),
        ),
    ]
