# Generated by Django 4.0.1 on 2022-01-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type of route', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='gpx',
            field=models.FileField(blank=True, null=True, upload_to='gpx'),
        ),
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='route.type'),
        ),
    ]
