# Generated by Django 4.0.1 on 2022-01-26 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('route', '0003_type_route_gpx_route_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoutePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(help_text='Give a comment', max_length=200)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='route.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the hike')),
                ('comment', models.TextField(help_text='Description of the route', max_length=1000)),
                ('score', models.DecimalField(decimal_places=1, help_text='Score for the route', max_digits=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='route.route')),
            ],
            options={
                'ordering': ['route', 'date'],
            },
        ),
    ]
